name: Apply Terraform Changes

on:
  push:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@
      
    # Log in to Azure using OIDC (recommended for security)
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: infra

    # Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate
      working-directory: infra

    # Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -out=tfplan -var="azure_search_api_key=${{ secrets.AZURE_AISEARCH_APIKEY }}" -var="azure_search_service_name=${{ secrets.AZURE_AISEARCH_SERVICENAME }}" -var="azure_search_index_name=${{ secrets.AZURE_AISEARCH_INDEXNAME }}" -var="azure_search_endpoint=${{ secrets.AZURE_AISEARCH_ENDPOINT }}"
      working-directory: infra

    # Apply Terraform changes
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: infra




      